# Data Cleaning Script — Q-Commerce Raw Files

In [736]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mysql.connector
import sqlalchemy
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [737]:
INPUT_DIR  = "Existing-Files"
OUTPUT_DIR = "Output-files"
sku_mapping = pd.read_csv("/Users/akshaybisht/Desktop/E-Automation/Existing-Files/sku-mapping.csv")
city_mapping = pd.read_csv("/Users/akshaybisht/Desktop/E-Automation/Existing-Files/city-mapping.csv")

## SKU Mapping Cleaning

In [738]:
sku_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   internal_sku_id       50 non-null     int64
 1   Category              50 non-null     object
 2   SKU                   50 non-null     object
 3   MRP                   50 non-null     int64
 4   Blinkit Identifier    22 non-null     float64
 5   Status                50 non-null     object
 6   Instamart Identifier  21 non-null     float64
 7   Status.1              50 non-null     object
 8   Zepto Identifier      37 non-null     object
 9   Status.2              50 non-null     object
 10  FKM Identifier        10 non-null     object
 11  Status.3              50 non-null     object
 12  BB Identifier         16 non-null     float64
 13  Status.4              50 non-null     object
dtypes: float64(3), int64(2), object(9)
memory usage: 5.6+ KB

In [739]:
for obj_col in sku_mapping.select_dtypes(include = "object"):
    sku_mapping[obj_col] = sku_mapping[obj_col].astype("string").str.strip()
sku_mapping.rename(columns={"Blinkit Identifier":"blinkit_identifier",
                            "Instamart Identifier":"instamart_identifier",
                            "Zepto Identifier":"zepto_identifier",
                            "FKM Identifier":"FKM_identifier",
                            "BB Identifier":"BB_identifier",
                            "Sumo ID":"internal_id",
                            "SKU":"internal_name",
                            "Status":"blinkit_status",
                            "Status.1":"instamart_status",
                            "Status.2":"zepto_status",
                            "Status.3":"FKM_status",
                            "Status.4":"BB_status"}, inplace=True)

## City Mapping Cleaning

In [740]:
city_mapping.rename(columns= {"Original CITY":"original_city_name",
                              "Standardised Name":"standardised_name",
                              "STATE":"state",
                              "REGION":"region"}, inplace= True)
for object_city_mapping in city_mapping.select_dtypes(include = "object"):
    city_mapping[object_city_mapping] = city_mapping[object_city_mapping].astype("string").str.strip()

city_mapping.drop_duplicates(subset=["original_city_name"], keep= "last", inplace=True)
city_mapping.reset_index(inplace=True)
city_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341 entries, 0 to 340
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               341 non-null    int64
 1   original_city_name  341 non-null    string
 2   standardised_name   341 non-null    string
 3   state               341 non-null    string
 4   region              341 non-null    string
 5   city_id             341 non-null    int64
dtypes: int64(2), string(4)
memory usage: 16.1 KB

## 1. Blinkit

### Prepping the Dump

In [741]:
df_blinkit = pd.read_csv(f"{INPUT_DIR}/blinkit-raw.csv", low_memory=False)

df_blinkit.drop(columns=["Internal SKU"], inplace=True)
df_blinkit = df_blinkit[["item_id", "item_name", "manufacturer_id", "manufacturer_name",
                          "city_id", "city_name", "category", "date", "qty_sold", "mrp"]]

for col in df_blinkit.select_dtypes(include="object"):
    df_blinkit[col] = df_blinkit[col].str.strip().astype("string")

df_blinkit["item_id"]         = pd.to_numeric(df_blinkit["item_id"])
df_blinkit["manufacturer_id"] = pd.to_numeric(df_blinkit["manufacturer_id"])
df_blinkit["city_id"]         = pd.to_numeric(df_blinkit["city_id"])
df_blinkit["qty_sold"]        = pd.to_numeric(df_blinkit["qty_sold"])
df_blinkit["mrp"]             = pd.to_numeric(df_blinkit["mrp"])
df_blinkit["date"]            = pd.to_datetime(df_blinkit["date"], dayfirst=True)

df_blinkit.drop_duplicates(inplace=True)
df_blinkit.sort_values("date", inplace=True)

In [742]:
df_blinkit.rename(columns={"item_id":"blinkit_identifier",
                           "item_name":"blinkit_name",
                           "item_id":"blinkit_identifier",
                           "city_name":"original_city_name"}, inplace=True)

In [743]:
df_blinkit.info()
df_blinkit.head()

<class 'pandas.core.frame.DataFrame'>
Index: 242984 entries, 0 to 242983
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   blinkit_identifier  242984 non-null  int64
 1   blinkit_name        242984 non-null  string
 2   manufacturer_id     242984 non-null  int64
 3   manufacturer_name   242984 non-null  string
 4   city_id             242984 non-null  int64
 5   original_city_name  242984 non-null  string
 6   category            242984 non-null  string
 7   date                242984 non-null  datetime64[ns]
 8   qty_sold            242984 non-null  int64
 9   mrp                 242984 non-null  int64
dtypes: datetime64[ns](1), int64(5), string(4)
memory usage: 20.4 MB

,blinkit_identifier,blinkit_name,manufacturer_id,manufacturer_name,city_id,original_city_name,category,date,qty_sold,mrp
0,16274339,Jaldhara Nimbu Shikanji Instant Drink Mix(Pack),1001,Jaldhara Drinks Pvt. Ltd.,12,Jaipur,Sports Drinks,2024-04-01,2,658
215,13240186,Jaldhara Gur Shikanji Instant Drink Premix Reg...,1001,Jaldhara Drinks Pvt. Ltd.,9,Gurgaon,Sports Drinks,2024-04-01,5,1045
214,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,113,Anand,Sports Drinks,2024-04-01,1,139
213,13240186,Jaldhara Gur Shikanji Instant Drink Premix Reg...,1001,Jaldhara Drinks Pvt. Ltd.,10,Ghaziabad,Sports Drinks,2024-04-01,1,209
212,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,2,Mumbai,Sports Drinks,2024-04-01,24,3336

#### Prepping SKU MAPPING to MERGE with DUMP

In [744]:
sku_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   internal_sku_id       50 non-null     int64
 1   Category              50 non-null     string
 2   internal_name         50 non-null     string
 3   MRP                   50 non-null     int64
 4   blinkit_identifier    22 non-null     float64
 5   blinkit_status        50 non-null     string
 6   instamart_identifier  21 non-null     float64
 7   instamart_status      50 non-null     string
 8   zepto_identifier      37 non-null     string
 9   zepto_status          50 non-null     string
 10  FKM_identifier        10 non-null     string
 11  FKM_status            50 non-null     string
 12  BB_identifier         16 non-null     float64
 13  BB_status             50 non-null     string
dtypes: float64(3), int64(2), string(9)
memory usage: 5.6 KB

In [745]:
sku_mapping_blinkit = sku_mapping[["blinkit_identifier","internal_sku_id","internal_name","Category",'blinkit_status']].copy()
sku_mapping_blinkit.head()

,blinkit_identifier,internal_sku_id,internal_name,Category,blinkit_status
0,16777627.0,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,16274339.0,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,17133772.0,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Live
3,16082268.0,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,18442218.0,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [746]:
blinkit_base = df_blinkit.merge(sku_mapping_blinkit, on="blinkit_identifier", how="left")
blinkit_base.head()

,blinkit_identifier,blinkit_name,manufacturer_id,manufacturer_name,city_id,original_city_name,category,date,qty_sold,mrp,internal_sku_id,internal_name,Category,blinkit_status
0,16274339,Jaldhara Nimbu Shikanji Instant Drink Mix(Pack),1001,Jaldhara Drinks Pvt. Ltd.,12,Jaipur,Sports Drinks,2024-04-01,2,658,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
1,13240186,Jaldhara Gur Shikanji Instant Drink Premix Reg...,1001,Jaldhara Drinks Pvt. Ltd.,9,Gurgaon,Sports Drinks,2024-04-01,5,1045,6102,Jaldhara Gur Shikanji Premix Pack of 15,Energy Mix,Discontinue
2,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,113,Anand,Sports Drinks,2024-04-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
3,13240186,Jaldhara Gur Shikanji Instant Drink Premix Reg...,1001,Jaldhara Drinks Pvt. Ltd.,10,Ghaziabad,Sports Drinks,2024-04-01,1,209,6102,Jaldhara Gur Shikanji Premix Pack of 15,Energy Mix,Discontinue
4,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,2,Mumbai,Sports Drinks,2024-04-01,24,3336,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live

#### Merging City Column

In [747]:
blinkit_base = blinkit_base.merge(city_mapping, how = "left", on = "original_city_name")
blinkit_base['platform_id'] = 1
blinkit_base.head()

,blinkit_identifier,blinkit_name,manufacturer_id,manufacturer_name,city_id_x,original_city_name,category,date,qty_sold,mrp,internal_sku_id,internal_name,Category,blinkit_status,index,standardised_name,state,region,city_id_y,platform_id
0,16274339,Jaldhara Nimbu Shikanji Instant Drink Mix(Pack),1001,Jaldhara Drinks Pvt. Ltd.,12,Jaipur,Sports Drinks,2024-04-01,2,658,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live,106.0,Jaipur,Rajasthan,West,406007.0,1
1,13240186,Jaldhara Gur Shikanji Instant Drink Premix Reg...,1001,Jaldhara Drinks Pvt. Ltd.,9,Gurgaon,Sports Drinks,2024-04-01,5,1045,6102,Jaldhara Gur Shikanji Premix Pack of 15,Energy Mix,Discontinue,282.0,Gurgaon,Haryana,North,202006.0,1
2,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,113,Anand,Sports Drinks,2024-04-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,13.0,Anand,Gujarat,West,403002.0,1
3,13240186,Jaldhara Gur Shikanji Instant Drink Premix Reg...,1001,Jaldhara Drinks Pvt. Ltd.,10,Ghaziabad,Sports Drinks,2024-04-01,1,209,6102,Jaldhara Gur Shikanji Premix Pack of 15,Energy Mix,Discontinue,81.0,Ghaziabad,Uttar Pradesh,Delhi NCR,103002.0,1
4,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,2,Mumbai,Sports Drinks,2024-04-01,24,3336,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,161.0,Mumbai,Maharashtra,West,405011.0,1

### Final Blinkit DF

In [748]:
blinkit_base = blinkit_base[['platform_id','blinkit_identifier','city_id_y','standardised_name','state','region','date','internal_sku_id','blinkit_status','Category','internal_name','qty_sold','mrp']].copy()
blinkit_base.rename(columns={
                            'blinkit_identifier' : 'platform_sku_id',
                            'date'               : 'sale_date',
                            'city_id_y'          : 'city_id',
                            "internal_id"        : 'internal_sku_id',
                            'standardised_name':'city_name',
                            'Category':'category',
                            "blinkit_status": "status"}, inplace=True)
blinkit_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,1,16274339,406007.0,Jaipur,Rajasthan,West,2024-04-01,3814,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 225g,2,658
1,1,13240186,202006.0,Gurgaon,Haryana,North,2024-04-01,6102,Discontinue,Energy Mix,Jaldhara Gur Shikanji Premix Pack of 15,5,1045
2,1,16777627,403002.0,Anand,Gujarat,West,2024-04-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139
3,1,13240186,103002.0,Ghaziabad,Uttar Pradesh,Delhi NCR,2024-04-01,6102,Discontinue,Energy Mix,Jaldhara Gur Shikanji Premix Pack of 15,1,209
4,1,16777627,405011.0,Mumbai,Maharashtra,West,2024-04-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,24,3336

## 2. Zepto

In [749]:
df_zepto = pd.read_csv(f"{INPUT_DIR}/zepto-raw.csv", low_memory=False)
df_zepto.head()

,Date,SKU Name,SKU ID,City,Brand Name,Manufacturer ID,Manufacturer Name,SKU Category,Quantity,GMV
0,01/04/2024,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",11,1419
1,01/04/2024,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Patna,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",7,903
2,01/04/2024,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Noida,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",19,2451
3,01/04/2024,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Surat,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",11,1419
4,01/04/2024,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Coimbatore,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",9,1161

In [750]:
df_zepto.rename(columns={
    "Date"           : "date",
    "SKU Name"         : "zepto_name",
    "SKU ID"           : "zepto_identifier",
    "City"           : "original_city_name",
    "Brand Name"       : "brand_name",
    "Manufacturer ID"  : "manufacture_id",
    "Manufacturer Name": "manufacture_name",
    "SKU Category"     : "sku_category",
    "Quantity"         : "quantity",
    "GMV"            : "gmv",
}, inplace=True)

df_zepto["date"] = pd.to_datetime(df_zepto["date"].str.replace("-", "/"), dayfirst=True)

for col in df_zepto.select_dtypes(include="object"):
    df_zepto[col] = df_zepto[col].str.strip().astype("string")

df_zepto.dropna(subset=["quantity"], inplace=True)
df_zepto.drop_duplicates(inplace=True)
df_zepto.sort_values("date", inplace=True)

In [751]:
df_zepto.info()
df_zepto.head()

<class 'pandas.core.frame.DataFrame'>
Index: 84988 entries, 0 to 84987
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                84988 non-null  datetime64[ns]
 1   zepto_name          84988 non-null  string
 2   zepto_identifier    84988 non-null  string
 3   original_city_name  84988 non-null  string
 4   brand_name          84988 non-null  string
 5   manufacture_id      84988 non-null  string
 6   manufacture_name    84988 non-null  string
 7   sku_category        84988 non-null  string
 8   quantity            84988 non-null  int64
 9   gmv                 84988 non-null  int64
dtypes: datetime64[ns](1), int64(2), string(7)
memory usage: 7.1 MB

,date,zepto_name,zepto_identifier,original_city_name,brand_name,manufacture_id,manufacture_name,sku_category,quantity,gmv
0,2024-04-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",11,1419
242,2024-04-01,Jaldhara Combo Iced Drink Mix Mango and Lemon ...,af512897-cb97-49a2-b495-20d4648773b1,Bhopal,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",7,1393
241,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Delhi,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",24,4296
240,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",7,1253
239,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Chandigarh,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",4,716

#### Prepping SKU MAPPING to MERGE with DUMP

In [752]:
sku_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   internal_sku_id       50 non-null     int64
 1   Category              50 non-null     string
 2   internal_name         50 non-null     string
 3   MRP                   50 non-null     int64
 4   blinkit_identifier    22 non-null     float64
 5   blinkit_status        50 non-null     string
 6   instamart_identifier  21 non-null     float64
 7   instamart_status      50 non-null     string
 8   zepto_identifier      37 non-null     string
 9   zepto_status          50 non-null     string
 10  FKM_identifier        10 non-null     string
 11  FKM_status            50 non-null     string
 12  BB_identifier         16 non-null     float64
 13  BB_status             50 non-null     string
dtypes: float64(3), int64(2), string(9)
memory usage: 5.6 KB

In [753]:
sku_mapping_zepto = sku_mapping[["zepto_identifier","internal_sku_id","internal_name","Category","zepto_status"]].copy()
sku_mapping_zepto.head()

,zepto_identifier,internal_sku_id,internal_name,Category,zepto_status
0,e60c96b4-afc6-47cd-a732-3317572ba370,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,73316a9f-0bfe-41ae-8a77-1c4b6647ffa1,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,b5e8fcfb-d267-4df8-b54c-1154b6a01027,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Live
3,02f8acdf-bc5e-4970-912e-feadc184c785,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,8497232c-cb60-4d49-9a8c-fc388c0a7b2d,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [754]:
zepto_base = df_zepto.merge(sku_mapping_zepto, on = "zepto_identifier", how = "left")
zepto_base.head()

,date,zepto_name,zepto_identifier,original_city_name,brand_name,manufacture_id,manufacture_name,sku_category,quantity,gmv,internal_sku_id,internal_name,Category,zepto_status
0,2024-04-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",11,1419,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,2024-04-01,Jaldhara Combo Iced Drink Mix Mango and Lemon ...,af512897-cb97-49a2-b495-20d4648773b1,Bhopal,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",7,1393,6112,Jaldhara Combo Mix Box Mango & Lemon,Energy Mix,Discontinue
2,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Delhi,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",24,4296,6108,Jaldhara Hibiscus Cooler Mixs 25 pcs,Sherbet,Discontinue
3,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",7,1253,6108,Jaldhara Hibiscus Cooler Mixs 25 pcs,Sherbet,Discontinue
4,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Chandigarh,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",4,716,6108,Jaldhara Hibiscus Cooler Mixs 25 pcs,Sherbet,Discontinue

#### Merging Cities

In [755]:
zepto_base = zepto_base.merge(city_mapping, how = "left", on = "original_city_name")
zepto_base['platform_id'] = 2
zepto_base.head()

,date,zepto_name,zepto_identifier,original_city_name,brand_name,manufacture_id,manufacture_name,sku_category,quantity,gmv,internal_sku_id,internal_name,Category,zepto_status,index,standardised_name,state,region,city_id,platform_id
0,2024-04-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Tea, Coffee & More",11,1419,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,134.0,Kolkata,West Bengal,East,507008.0,2
1,2024-04-01,Jaldhara Combo Iced Drink Mix Mango and Lemon ...,af512897-cb97-49a2-b495-20d4648773b1,Bhopal,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",7,1393,6112,Jaldhara Combo Mix Box Mango & Lemon,Energy Mix,Discontinue,40.0,Bhopal,Madhya Pradesh,West,404001.0,2
2,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Delhi,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",24,4296,6108,Jaldhara Hibiscus Cooler Mixs 25 pcs,Sherbet,Discontinue,61.0,Delhi,Delhi,Delhi NCR,101001.0,2
3,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",7,1253,6108,Jaldhara Hibiscus Cooler Mixs 25 pcs,Sherbet,Discontinue,134.0,Kolkata,West Bengal,East,507008.0,2
4,2024-04-01,Jaldhara Hibiscus Cooler Herbal Drink Bags 25....,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,Chandigarh,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",4,716,6108,Jaldhara Hibiscus Cooler Mixs 25 pcs,Sherbet,Discontinue,52.0,Chandigarh,Chandigarh,North,201001.0,2

### Final Zepto Dataframe

In [756]:
zepto_base = zepto_base[['platform_id','zepto_identifier','city_id','standardised_name','state','region','date','internal_sku_id',"zepto_status",'Category','internal_name','quantity','gmv']].copy()
zepto_base.rename(columns={
                            'zepto_identifier' : 'platform_sku_id',
                            'date'               : 'sale_date',
                            "internal_id"        : 'internal_sku_id',
                            'standardised_name':'city_name',
                            "Category":'category',
                            'quantity' : 'qty_sold',
                            'gmv' : 'mrp',
                            "zepto_status":"status"}, inplace=True)
zepto_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,2,e60c96b4-afc6-47cd-a732-3317572ba370,507008.0,Kolkata,West Bengal,East,2024-04-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,11,1419
1,2,af512897-cb97-49a2-b495-20d4648773b1,404001.0,Bhopal,Madhya Pradesh,West,2024-04-01,6112,Discontinue,Energy Mix,Jaldhara Combo Mix Box Mango & Lemon,7,1393
2,2,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,101001.0,Delhi,Delhi,Delhi NCR,2024-04-01,6108,Discontinue,Sherbet,Jaldhara Hibiscus Cooler Mixs 25 pcs,24,4296
3,2,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,507008.0,Kolkata,West Bengal,East,2024-04-01,6108,Discontinue,Sherbet,Jaldhara Hibiscus Cooler Mixs 25 pcs,7,1253
4,2,9de5c6f0-1042-40b7-9c06-c5f48dc42b15,201001.0,Chandigarh,Chandigarh,North,2024-04-01,6108,Discontinue,Sherbet,Jaldhara Hibiscus Cooler Mixs 25 pcs,4,716

## 3. Instamart

In [757]:
df_instamart = pd.read_csv(f"{INPUT_DIR}/instamart-raw.csv", low_memory=False)


for col in df_instamart.select_dtypes(include="object"):
    df_instamart[col] = df_instamart[col].str.strip().astype("string")

df_instamart.rename(columns={"GMV.1": "GMV",
                             "PRODUCT_NAME": "instamart_name",
                             "ITEM_CODE":"instamart_identifier",
                             "CITY":"original_city_name"}, inplace=True)
df_instamart["ORDERED_DATE"] = pd.to_datetime(df_instamart["ORDERED_DATE"], dayfirst=True, format="mixed")
df_instamart.sort_values("ORDERED_DATE", inplace=True)
df_instamart.drop_duplicates(inplace=True)

In [758]:
df_instamart.info()
df_instamart.head()

<class 'pandas.core.frame.DataFrame'>
Index: 114619 entries, 0 to 114744
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   DATE                  114619 non-null  string
 1   ORDERED_DATE          114619 non-null  datetime64[ns]
 2   original_city_name    114619 non-null  string
 3   AREA_NAME             114619 non-null  string
 4   STORE_ID              114619 non-null  int64
 5   L1_CATEGORY           114619 non-null  string
 6   L2_CATEGORY           114619 non-null  string
 7   L3_CATEGORY           114619 non-null  string
 8   instamart_name        114619 non-null  string
 9   VARIANT               114619 non-null  string
 10  instamart_identifier  114619 non-null  int64
 11  COMBO                 114619 non-null  string
 12  COMBO_ITEM_CODE       14793 non-null   float64
 13  COMBO_UNITS_SOLD      14793 non-null   float64
 14  BASE_MRP              114619 non-null  int64
 15  UNITS_SOLD            114619 non-null  int64
 16  GMV                   114619 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(5), string(9)
memory usage: 15.7 MB

,DATE,ORDERED_DATE,original_city_name,AREA_NAME,STORE_ID,L1_CATEGORY,L2_CATEGORY,L3_CATEGORY,instamart_name,VARIANT,instamart_identifier,COMBO,COMBO_ITEM_CODE,COMBO_UNITS_SOLD,BASE_MRP,UNITS_SOLD,GMV
0,jaldhara,2024-04-01,Lucknow,hazratganj,1399004,summer drinks and snacks,tea,drink mixes,jaldhara nimbu shikanji - premium instant drin...,225 g,962270,Yes,880235.0,1.0,189,9,1701
146,jaldhara,2024-04-01,Mumbai,andheri west,1395000,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,453209,No,NaN,NaN,149,12,1788
147,jaldhara,2024-04-01,Jaipur,malviya nagar,1398003,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,453209,No,NaN,NaN,149,2,298
148,jaldhara,2024-04-01,Chennai,royapettah,1400603,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,453209,Yes,53245.0,1.0,149,5,745
149,jaldhara,2024-04-01,Pune,koregaon park,1396001,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,453209,No,NaN,NaN,149,3,447

#### Prepping SKU MAPPING to MERGE with DUMP

In [759]:
sku_mapping_instamart = sku_mapping[["instamart_identifier","internal_sku_id","internal_name","Category","instamart_status"]].copy()
sku_mapping_instamart.head()

,instamart_identifier,internal_sku_id,internal_name,Category,instamart_status
0,NaN,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Not - Live
1,962270.0,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,313662.0,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Live
3,NaN,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Not - Live
4,792374.0,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [760]:
instamart_base = df_instamart.merge(sku_mapping_instamart, on = "instamart_identifier", how = "left")
instamart_base.head()

,DATE,ORDERED_DATE,original_city_name,AREA_NAME,STORE_ID,L1_CATEGORY,L2_CATEGORY,L3_CATEGORY,instamart_name,VARIANT,...,COMBO,COMBO_ITEM_CODE,COMBO_UNITS_SOLD,BASE_MRP,UNITS_SOLD,GMV,internal_sku_id,internal_name,Category,instamart_status
0,jaldhara,2024-04-01,Lucknow,hazratganj,1399004,summer drinks and snacks,tea,drink mixes,jaldhara nimbu shikanji - premium instant drin...,225 g,...,Yes,880235.0,1.0,189,9,1701,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
1,jaldhara,2024-04-01,Mumbai,andheri west,1395000,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,No,NaN,NaN,149,12,1788,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live
2,jaldhara,2024-04-01,Jaipur,malviya nagar,1398003,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,No,NaN,NaN,149,2,298,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live
3,jaldhara,2024-04-01,Chennai,royapettah,1400603,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,Yes,53245.0,1.0,149,5,745,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live
4,jaldhara,2024-04-01,Pune,koregaon park,1396001,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,No,NaN,NaN,149,3,447,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live

#### Merging Cities

In [761]:
instamart_base =instamart_base.merge(city_mapping, how = "left", on = "original_city_name")
instamart_base['platform_id'] = 3
instamart_base.head()

,DATE,ORDERED_DATE,original_city_name,AREA_NAME,STORE_ID,L1_CATEGORY,L2_CATEGORY,L3_CATEGORY,instamart_name,VARIANT,...,internal_sku_id,internal_name,Category,instamart_status,index,standardised_name,state,region,city_id,platform_id
0,jaldhara,2024-04-01,Lucknow,hazratganj,1399004,summer drinks and snacks,tea,drink mixes,jaldhara nimbu shikanji - premium instant drin...,225 g,...,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live,145,Lucknow,Uttar Pradesh,North,207024,3
1,jaldhara,2024-04-01,Mumbai,andheri west,1395000,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live,161,Mumbai,Maharashtra,West,405011,3
2,jaldhara,2024-04-01,Jaipur,malviya nagar,1398003,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live,106,Jaipur,Rajasthan,West,406007,3
3,jaldhara,2024-04-01,Chennai,royapettah,1400603,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live,55,Chennai,Tamil Nadu,South,305001,3
4,jaldhara,2024-04-01,Pune,koregaon park,1396001,summer drinks and snacks,instant drink mixes,combo,"jaldhara instant drink mix combo, 210 grams, n...",210 g,...,5640,Jaldhara Combo Cooler Pack of 15,Energy Mix,Live,193,Pune,Maharashtra,West,405015,3

### Final Instamart Dataframe

In [762]:
instamart_base = instamart_base[['platform_id','instamart_identifier','city_id','standardised_name','state','region','ORDERED_DATE','internal_sku_id','instamart_status','Category','internal_name','UNITS_SOLD','GMV']].copy()
instamart_base.rename(columns={
                            'instamart_identifier' : 'platform_sku_id',
                            'ORDERED_DATE'               : 'sale_date',
                            "internal_id"        : 'internal_sku_id',
                            'standardised_name':'city_name',
                            'Category':'category',
                            'UNITS_SOLD':"qty_sold",
                            "GMV":'mrp',
                            'instamart_status':"status"}, inplace=True)
instamart_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,3,962270,207024,Lucknow,Uttar Pradesh,North,2024-04-01,3814,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 225g,9,1701
1,3,453209,405011,Mumbai,Maharashtra,West,2024-04-01,5640,Live,Energy Mix,Jaldhara Combo Cooler Pack of 15,12,1788
2,3,453209,406007,Jaipur,Rajasthan,West,2024-04-01,5640,Live,Energy Mix,Jaldhara Combo Cooler Pack of 15,2,298
3,3,453209,305001,Chennai,Tamil Nadu,South,2024-04-01,5640,Live,Energy Mix,Jaldhara Combo Cooler Pack of 15,5,745
4,3,453209,405015,Pune,Maharashtra,West,2024-04-01,5640,Live,Energy Mix,Jaldhara Combo Cooler Pack of 15,3,447

## 4. FK Minutes

In [763]:
df_fkminutes = pd.read_csv(f"{INPUT_DIR}/fkminutes-raw.csv", low_memory=False)


for col in df_fkminutes.select_dtypes(include="object"):
    df_fkminutes[col] = df_fkminutes[col].str.strip().astype("string")

# Normalise date string and truncate to date part only
df_fkminutes["order_date_time"] = (
    df_fkminutes["order_date_time"]
    .str.replace("-", "/")
    .str[:10]
)
df_fkminutes["order_date_time"] = pd.to_datetime(df_fkminutes["order_date_time"], dayfirst=True, format="mixed")
df_fkminutes.sort_values("order_date_time", inplace=True)
df_fkminutes.drop_duplicates(inplace=True)

In [764]:
df_fkminutes.rename(columns={"product_id":"FKM_identifier",
                             "city":"original_city_name"}, inplace = True)

In [765]:
df_fkminutes.info()
df_fkminutes.head()

<class 'pandas.core.frame.DataFrame'>
Index: 6922 entries, 0 to 6921
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   BrandName_gsheet         6922 non-null   string
 1   order_date_time          6922 non-null   datetime64[ns]
 2   original_city_name       6921 non-null   string
 3   FKM_identifier           6922 non-null   string
 4   analytic_business_unit   6922 non-null   string
 5   analytic_super_category  6922 non-null   string
 6   analytic_vertical        6922 non-null   string
 7   brand_csv                6922 non-null   string
 8   units                    6922 non-null   int64
 9   mrp                      6922 non-null   int64
dtypes: datetime64[ns](1), int64(2), string(7)
memory usage: 594.9 KB

,BrandName_gsheet,order_date_time,original_city_name,FKM_identifier,analytic_business_unit,analytic_super_category,analytic_vertical,brand_csv,units,mrp
0,Jaldhara,2024-10-01,Patna,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139
22,Jaldhara,2024-10-01,Bangalore,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,5,695
21,Jaldhara,2024-10-01,Kolkata,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139
20,Jaldhara,2024-10-01,Delhi,COOLK89IUXAK4R2G,BGM,FoodAndNutrition,Drinks,Jaldhara,4,1396
18,Jaldhara,2024-10-01,Mumbai,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,3,417

### Prepping SKU MAPPING to MERGE with DUMP

In [766]:
sku_mapping_fkminutes = sku_mapping[["FKM_identifier","internal_sku_id","internal_name","Category","FKM_status"]].copy()
sku_mapping_fkminutes.head()

,FKM_identifier,internal_sku_id,internal_name,Category,FKM_status
0,COOLHGI1JNYT7RPW,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,COOLNYFX4M8T1QOJ,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,<NA>,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Not - Live
3,COOL9TQ6V9MH7F2V,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,COOLGDGYP7WFWNEO,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [767]:
fkminutes_base = df_fkminutes.merge(sku_mapping_fkminutes, on = "FKM_identifier", how = "left")
fkminutes_base.head()

,BrandName_gsheet,order_date_time,original_city_name,FKM_identifier,analytic_business_unit,analytic_super_category,analytic_vertical,brand_csv,units,mrp,internal_sku_id,internal_name,Category,FKM_status
0,Jaldhara,2024-10-01,Patna,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
1,Jaldhara,2024-10-01,Bangalore,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,5,695,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
2,Jaldhara,2024-10-01,Kolkata,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
3,Jaldhara,2024-10-01,Delhi,COOLK89IUXAK4R2G,BGM,FoodAndNutrition,Drinks,Jaldhara,4,1396,6106,Jaldhara Premium Kokum Sherbet 450g,Sherbet,Discontinue
4,Jaldhara,2024-10-01,Mumbai,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,3,417,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live

#### Merging Cities

In [768]:
fkminutes_base = fkminutes_base.merge(city_mapping, how = "left", on = "original_city_name")
fkminutes_base['platform_id'] = 4
fkminutes_base.head()

,BrandName_gsheet,order_date_time,original_city_name,FKM_identifier,analytic_business_unit,analytic_super_category,analytic_vertical,brand_csv,units,mrp,internal_sku_id,internal_name,Category,FKM_status,index,standardised_name,state,region,city_id,platform_id
0,Jaldhara,2024-10-01,Patna,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live,187.0,Patna,Bihar,East,502011.0,4
1,Jaldhara,2024-10-01,Bangalore,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,5,695,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,21.0,Bangalore,Karnataka,South,302002.0,4
2,Jaldhara,2024-10-01,Kolkata,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live,134.0,Kolkata,West Bengal,East,507008.0,4
3,Jaldhara,2024-10-01,Delhi,COOLK89IUXAK4R2G,BGM,FoodAndNutrition,Drinks,Jaldhara,4,1396,6106,Jaldhara Premium Kokum Sherbet 450g,Sherbet,Discontinue,61.0,Delhi,Delhi,Delhi NCR,101001.0,4
4,Jaldhara,2024-10-01,Mumbai,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,3,417,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,161.0,Mumbai,Maharashtra,West,405011.0,4

### Final Flipkart Minutes Dataframe

In [769]:
fkminutes_base = fkminutes_base[['platform_id','FKM_identifier','city_id','standardised_name','state','region','order_date_time','internal_sku_id',"FKM_status",'Category','internal_name','units','mrp']].copy()
fkminutes_base.rename(columns={
                            'FKM_identifier'       : 'platform_sku_id',
                            'order_date_time'      : 'sale_date',
                            "internal_id"          : 'internal_sku_id',
                            'standardised_name'    : 'city_name',
                            'Category'             : 'category',
                            'units'                : "qty_sold",
                            "FKM_status"           :  "status"}, inplace=True)
fkminutes_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,4,COOL9TQ6V9MH7F2V,502011.0,Patna,Bihar,East,2024-10-01,2309,Live,Lemonade,Jaldhara Kala Namak Lemonade Mix 90g,1,139
1,4,COOLHGI1JNYT7RPW,302002.0,Bangalore,Karnataka,South,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,5,695
2,4,COOL9TQ6V9MH7F2V,507008.0,Kolkata,West Bengal,East,2024-10-01,2309,Live,Lemonade,Jaldhara Kala Namak Lemonade Mix 90g,1,139
3,4,COOLK89IUXAK4R2G,101001.0,Delhi,Delhi,Delhi NCR,2024-10-01,6106,Discontinue,Sherbet,Jaldhara Premium Kokum Sherbet 450g,4,1396
4,4,COOLHGI1JNYT7RPW,405011.0,Mumbai,Maharashtra,West,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,3,417

## 5. Big Basket

In [770]:
df_bigbasket = pd.read_csv(f"{INPUT_DIR}/big-basket-raw.csv", low_memory=False)


for col in df_bigbasket.select_dtypes(include="object"):
    df_bigbasket[col] = df_bigbasket[col].str.strip().astype("string")

# Big Basket provides a date range string (YYYYMMDD) — split into start and end dates
df_bigbasket["start_date"] = pd.to_datetime(df_bigbasket["date_range"].str[:8],  format="%Y%m%d", errors="coerce")
df_bigbasket["end_date"]   = pd.to_datetime(df_bigbasket["date_range"].str[-8:], format="%Y%m%d", errors="coerce")

df_bigbasket = df_bigbasket[["start_date", "end_date", "date_range", "source_city_name", "brand_name",
                              "top_slug", "mid_slug", "leaf_slug", "source_sku_id", "sku_description",
                              "sku_weight", "total_quantity", "total_mrp", "total_sales"]]
df_bigbasket.drop_duplicates(inplace=True)

In [771]:
df_bigbasket.rename(columns={"source_sku_id":"BB_identifier",
                             "source_city_name":"original_city_name"}, inplace=True)

In [772]:
df_bigbasket.info()
df_bigbasket.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 585 entries, 0 to 584
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   start_date          585 non-null    datetime64[ns]
 1   end_date            585 non-null    datetime64[ns]
 2   date_range          585 non-null    string
 3   original_city_name  585 non-null    string
 4   brand_name          585 non-null    string
 5   top_slug            585 non-null    string
 6   mid_slug            585 non-null    string
 7   leaf_slug           585 non-null    string
 8   BB_identifier       585 non-null    int64
 9   sku_description     585 non-null    string
 10  sku_weight          585 non-null    string
 11  total_quantity      585 non-null    int64
 12  total_mrp           585 non-null    int64
 13  total_sales         585 non-null    float64
dtypes: datetime64[ns](2), float64(1), int64(3), string(8)
memory usage: 64.1 KB

,start_date,end_date,date_range,original_city_name,brand_name,top_slug,mid_slug,leaf_slug,BB_identifier,sku_description,sku_weight,total_quantity,total_mrp,total_sales
0,2024-10-01,2024-10-31,20241001 - 20241031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,47448644,Jaldhara rose-sharbat-concentrate 150 g,150 g,61,11539,9480.20
1,2024-10-01,2024-10-31,20241001 - 20241031,Gurgaon,Jaldhara,beverages,tea,leaf-dust-tea,40929456,Jaldhara kala-namak-lemonade-instant-drink-mix...,225 g,2,658,558.00
2,2024-10-01,2024-10-31,20241001 - 20241031,Mumbai,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,48004382,Jaldhara instant-orange-electrolyte-drink-mix ...,330 g,8,1512,1329.11
3,2024-10-01,2024-10-31,20241001 - 20241031,Mumbai,Jaldhara,beverages,energy-soft-drinks,icetea-non-aerated-drink,42410255,Jaldhara instant-mango-iced-drink-premix 220 g...,220 g,27,3213,2588.47
4,2024-10-01,2024-10-31,20241001 - 20241031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,43792419,Jaldhara kewra-sharbat-concentrate-herbal-drin...,150 g,23,4807,3922.35

### Prepping SKU MAPPING to MERGE with DUMP

In [773]:
sku_mapping_bigbasket = sku_mapping[["BB_identifier","internal_sku_id","internal_name","Category","BB_status"]].copy()
sku_mapping_bigbasket.head()

,BB_identifier,internal_sku_id,internal_name,Category,BB_status
0,43635493.0,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,40127838.0,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,NaN,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Not - Live
3,42980060.0,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,40929456.0,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [774]:
bigbasket_base = df_bigbasket.merge(sku_mapping_bigbasket, on = "BB_identifier", how = "left")
bigbasket_base.head()

,start_date,end_date,date_range,original_city_name,brand_name,top_slug,mid_slug,leaf_slug,BB_identifier,sku_description,sku_weight,total_quantity,total_mrp,total_sales,internal_sku_id,internal_name,Category,BB_status
0,2024-10-01,2024-10-31,20241001 - 20241031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,47448644,Jaldhara rose-sharbat-concentrate 150 g,150 g,61,11539,9480.20,1870,Jaldhara Rose Sherbet Mix,Sherbet,Live
1,2024-10-01,2024-10-31,20241001 - 20241031,Gurgaon,Jaldhara,beverages,tea,leaf-dust-tea,40929456,Jaldhara kala-namak-lemonade-instant-drink-mix...,225 g,2,658,558.00,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live
2,2024-10-01,2024-10-31,20241001 - 20241031,Mumbai,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,48004382,Jaldhara instant-orange-electrolyte-drink-mix ...,330 g,8,1512,1329.11,4860,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live
3,2024-10-01,2024-10-31,20241001 - 20241031,Mumbai,Jaldhara,beverages,energy-soft-drinks,icetea-non-aerated-drink,42410255,Jaldhara instant-mango-iced-drink-premix 220 g...,220 g,27,3213,2588.47,5021,Jaldhara Mango Iced Drink Mix,Iced Mix,Live
4,2024-10-01,2024-10-31,20241001 - 20241031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,43792419,Jaldhara kewra-sharbat-concentrate-herbal-drin...,150 g,23,4807,3922.35,3560,Jaldhara Kewra Sherbet Mix,Sherbet,Live

#### Merging Cities

In [775]:
bigbasket_base = bigbasket_base.merge(city_mapping, how = "left", on = "original_city_name")
bigbasket_base['platform_id'] = 5
bigbasket_base.head()

,start_date,end_date,date_range,original_city_name,brand_name,top_slug,mid_slug,leaf_slug,BB_identifier,sku_description,...,internal_sku_id,internal_name,Category,BB_status,index,standardised_name,state,region,city_id,platform_id
0,2024-10-01,2024-10-31,20241001 - 20241031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,47448644,Jaldhara rose-sharbat-concentrate 150 g,...,1870,Jaldhara Rose Sherbet Mix,Sherbet,Live,21,Bangalore,Karnataka,South,302002,5
1,2024-10-01,2024-10-31,20241001 - 20241031,Gurgaon,Jaldhara,beverages,tea,leaf-dust-tea,40929456,Jaldhara kala-namak-lemonade-instant-drink-mix...,...,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live,282,Gurgaon,Haryana,North,202006,5
2,2024-10-01,2024-10-31,20241001 - 20241031,Mumbai,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,48004382,Jaldhara instant-orange-electrolyte-drink-mix ...,...,4860,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live,161,Mumbai,Maharashtra,West,405011,5
3,2024-10-01,2024-10-31,20241001 - 20241031,Mumbai,Jaldhara,beverages,energy-soft-drinks,icetea-non-aerated-drink,42410255,Jaldhara instant-mango-iced-drink-premix 220 g...,...,5021,Jaldhara Mango Iced Drink Mix,Iced Mix,Live,161,Mumbai,Maharashtra,West,405011,5
4,2024-10-01,2024-10-31,20241001 - 20241031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,43792419,Jaldhara kewra-sharbat-concentrate-herbal-drin...,...,3560,Jaldhara Kewra Sherbet Mix,Sherbet,Live,21,Bangalore,Karnataka,South,302002,5

In [776]:
bigbasket_base = bigbasket_base[['platform_id','BB_identifier','city_id','standardised_name','state','region','end_date','internal_sku_id',"BB_status",'Category','internal_name','total_quantity','total_mrp']].copy()
bigbasket_base.rename(columns={
                            'BB_identifier'       : 'platform_sku_id',
                            'end_date'      : 'sale_date',
                            "internal_id"          : 'internal_sku_id',
                            'standardised_name'    : 'city_name',
                            'total_quantity'                : "qty_sold",
                            "internal_name"       :      "internal_name",
                            'Category'      :   'category',
                            "total_mrp"                  : 'mrp',
                            "BB_status" : "status"}, inplace=True)
bigbasket_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,5,47448644,302002,Bangalore,Karnataka,South,2024-10-31,1870,Live,Sherbet,Jaldhara Rose Sherbet Mix,61,11539
1,5,40929456,202006,Gurgaon,Haryana,North,2024-10-31,3812,Live,Lemonade,Jaldhara Kala Namak Lemonade Mix 225g,2,658
2,5,48004382,405011,Mumbai,Maharashtra,West,2024-10-31,4860,Live,Energy Mix,Jaldhara Orange Electrolyte Pack of 20,8,1512
3,5,42410255,405011,Mumbai,Maharashtra,West,2024-10-31,5021,Live,Iced Mix,Jaldhara Mango Iced Drink Mix,27,3213
4,5,43792419,302002,Bangalore,Karnataka,South,2024-10-31,3560,Live,Sherbet,Jaldhara Kewra Sherbet Mix,23,4807

### CONCATENATING QCOM DATAFRAMES TO ONE

In [777]:
fact_sales = pd.concat([blinkit_base, zepto_base, instamart_base, fkminutes_base, bigbasket_base], ignore_index= True)
fact_sales.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,1,16274339,406007.0,Jaipur,Rajasthan,West,2024-04-01,3814,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 225g,2,658
1,1,13240186,202006.0,Gurgaon,Haryana,North,2024-04-01,6102,Discontinue,Energy Mix,Jaldhara Gur Shikanji Premix Pack of 15,5,1045
2,1,16777627,403002.0,Anand,Gujarat,West,2024-04-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139
3,1,13240186,103002.0,Ghaziabad,Uttar Pradesh,Delhi NCR,2024-04-01,6102,Discontinue,Energy Mix,Jaldhara Gur Shikanji Premix Pack of 15,1,209
4,1,16777627,405011.0,Mumbai,Maharashtra,West,2024-04-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,24,3336

In [778]:
fact_sales['city_id']         = fact_sales['city_id'].astype('Int64')
fact_sales['internal_sku_id'] = fact_sales['internal_sku_id'].astype('Int64')
fact_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 451678 entries, 0 to 451677
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   platform_id      451678 non-null  int64
 1   platform_sku_id  451678 non-null  object
 2   city_id          450511 non-null  Int64
 3   city_name        450511 non-null  string
 4   state            450511 non-null  string
 5   region           450511 non-null  string
 6   sale_date        451678 non-null  datetime64[ns]
 7   internal_sku_id  451678 non-null  Int64
 8   status           451678 non-null  string
 9   category         451678 non-null  string
 10  internal_name    451678 non-null  string
 11  qty_sold         451678 non-null  int64
 12  mrp              451678 non-null  int64
dtypes: Int64(2), datetime64[ns](1), int64(3), object(1), string(6)
memory usage: 45.7+ MB

In [779]:
fact_sales.groupby('platform_id')['sale_date'].min()

platform_id
1   2024-04-01
2   2024-04-01
3   2024-04-01
4   2024-10-01
5   2024-10-31
Name: sale_date, dtype: datetime64[ns]

In [780]:
fact_sales[fact_sales['internal_name'].isna()]

Empty DataFrame
Columns: [platform_id, platform_sku_id, city_id, city_name, state, region, sale_date, internal_sku_id, status, category, internal_name, qty_sold, mrp]
Index: []

## SQL DATABASE CREATION

In [781]:
# Connecting with the server
password = quote_plus("#Arti14@")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/jaldhara_db")

### fact_sales DF Schema Creation

In [782]:
fact_sales.to_sql(
    name      = "fact_sales",
    con       = engine,
    if_exists = "replace",
    index     = False,
    dtype     = {
        "platform_id"       : sqlalchemy.types.SmallInteger(),
        "platform_sku_id"   : sqlalchemy.types.VARCHAR(100),
        "city_id"           : sqlalchemy.types.VARCHAR(20),
        "city_name"         : sqlalchemy.types.VARCHAR(100),
        "state"             : sqlalchemy.types.VARCHAR(100),
        "region"            : sqlalchemy.types.VARCHAR(50),
        "sale_date"         : sqlalchemy.types.Date(),
        "internal_sku_id"   : sqlalchemy.types.Integer(),
        "sku_status"        : sqlalchemy.types.VARCHAR(20),
        "category"          : sqlalchemy.types.VARCHAR(50),
        "internal_sku_name" : sqlalchemy.types.VARCHAR(200),
        "qty_sold"          : sqlalchemy.types.Integer(),
        "mrp"               : sqlalchemy.types.Numeric(10, 2),
    }
)

451678

### dim_platform_sku_map DF Schema Creation

In [783]:
sku_mapping.to_sql(
    name      = "dim_platform_sku_map",
    con       = engine,
    if_exists = "replace",
    index     = False,
    dtype     = {
        "internal_sku_id"       : sqlalchemy.types.Integer(),
        "Category"              : sqlalchemy.types.VARCHAR(50),
        "internal_name"         : sqlalchemy.types.VARCHAR(50),
        "MRP"                   : sqlalchemy.types.Numeric(10, 2),
        "blinkit_identifier"    : sqlalchemy.types.Integer(),
        "blinkit_status"        : sqlalchemy.types.VARCHAR(20),
        "instamart_identifier"  : sqlalchemy.types.Integer(),
        "instamart_status"      : sqlalchemy.types.VARCHAR(20),
        "zepto_identifier"      : sqlalchemy.types.VARCHAR(50),
        "zepto_status"          : sqlalchemy.types.VARCHAR(20),
        "FKM_identifier"        : sqlalchemy.types.VARCHAR(50),
        "FKM_status"            : sqlalchemy.types.VARCHAR(20),
        "BB_identifier"         : sqlalchemy.types.Integer(),
        "BB_status"             : sqlalchemy.types.VARCHAR(20)
    }
)

50

### dim_sku DF Schema Creation

In [784]:
city_mapping = city_mapping[['city_id','original_city_name','standardised_name','state','region']]
city_mapping.reset_index(inplace=True, drop = True)
city_mapping.head()

   city_id original_city_name standardised_name          state region
0   207001               Agra              Agra  Uttar Pradesh  North
1   403001          Ahmedabad         Ahmedabad        Gujarat   West
2   405001         Ahmednagar        Ahmednagar    Maharashtra   West
3   406001              Ajmer             Ajmer      Rajasthan   West
4   405002              Akola             Akola    Maharashtra   West

In [785]:
city_mapping.to_sql(
    name      = "dim_city",
    con       = engine,
    if_exists = "replace",
    index     = False,
    dtype     = {
        "city_id"               : sqlalchemy.types.Integer(),
        "original_city_name"    : sqlalchemy.types.VARCHAR(100),
        "standardised_name"     : sqlalchemy.types.VARCHAR(100),
        "state"                 : sqlalchemy.types.VARCHAR(50),
        "region"                : sqlalchemy.types.VARCHAR(20)
    }
)

341

### dim_platforms DF Schema Creation

In [786]:
platforms = {"platform_id":[1,2,3,4,5],
             "platform_name":["Blinkit","Zepto","Instamart","Flipkart Minutes","Big Basket"],
             "Granularity":["Daily","Daily","Daily","Daily","From 1st of the Month"]}
platforms = pd.DataFrame(platforms)
platforms

   platform_id     platform_name            Granularity
0            1           Blinkit                  Daily
1            2             Zepto                  Daily
2            3         Instamart                  Daily
3            4  Flipkart Minutes                  Daily
4            5        Big Basket  From 1st of the Month

In [787]:
platforms.to_sql(
    name      = "dim_platform",
    con       = engine,
    if_exists = "replace",
    index     = False,
    dtype     = {
        "platform_id"               : sqlalchemy.types.SmallInteger(),
        "platform_name"             : sqlalchemy.types.VARCHAR(100),
        "Granularity"               : sqlalchemy.types.VARCHAR(100)
    }
)

5

In [788]:
all_sku = sku_mapping[['internal_sku_id','internal_name','Category']]
all_sku.drop_duplicates(subset=['internal_sku_id','internal_name','Category'])
all_sku.head()

   internal_sku_id                          internal_name  Category
0             2310        Jaldhara Nimbu Shikanji Mix 90g  Lemonade
1             3814       Jaldhara Nimbu Shikanji Mix 225g  Lemonade
2             4102       Jaldhara Nimbu Shikanji Mix 450g  Lemonade
3             2309   Jaldhara Kala Namak Lemonade Mix 90g  Lemonade
4             3812  Jaldhara Kala Namak Lemonade Mix 225g  Lemonade

In [789]:
all_sku.to_sql(
    name      = "dim_sku",
    con       = engine,
    if_exists = "replace",
    index     = False,
    dtype     = {
        "internal_sku_id"       : sqlalchemy.types.Integer(),
        "internal_name"         : sqlalchemy.types.VARCHAR(50),
        "Category"              : sqlalchemy.types.VARCHAR(50)
        }
)

50