# Data Cleaning Script — Q-Commerce Raw Files

In [951]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mysql.connector
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [952]:
INPUT_DIR  = "Existing-Files"
OUTPUT_DIR = "Output-files"
sku_mapping = pd.read_csv("/Users/akshaybisht/Desktop/E-Automation/Existing-Files/sku-mapping.csv")
city_mapping = pd.read_csv("/Users/akshaybisht/Desktop/E-Automation/Existing-Files/city-mapping.csv")

## SKU Mapping Cleaning

In [953]:
sku_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Sumo ID               50 non-null     int64
 1   Category              50 non-null     object
 2   SKU                   50 non-null     object
 3   MRP                   50 non-null     int64
 4   Blinkit Identifier    22 non-null     float64
 5   Status                50 non-null     object
 6   Instamart Identifier  20 non-null     float64
 7   Status.1              50 non-null     object
 8   Zepto Identifier      37 non-null     object
 9   Status.2              50 non-null     object
 10  FKM Identifier        10 non-null     object
 11  Status.3              50 non-null     object
 12  BB Identifier         16 non-null     float64
 13  Status.4              50 non-null     object
dtypes: float64(3), int64(2), object(9)
memory usage: 5.6+ KB

In [954]:
for obj_col in sku_mapping.select_dtypes(include = "object"):
    sku_mapping[obj_col] = sku_mapping[obj_col].astype("string").str.strip()
sku_mapping.rename(columns={"Blinkit Identifier":"blinkit_identifier",
                            "Instamart Identifier":"instamart_identifier",
                            "Zepto Identifier":"zepto_identifier",
                            "FKM Identifier":"FKM_identifier",
                            "BB Identifier":"BB_identifier",
                            "Sumo ID":"internal_id",
                            "SKU":"internal_name",
                            "Status":"blinkit_status",
                            "Status.1":"instamart_status",
                            "Status.2":"zepto_status",
                            "Status.3":"FKM_status",
                            "Status.4":"BB_status",}, inplace=True)

## City Mapping Cleaning

In [955]:
city_mapping.rename(columns= {"Original CITY":"original_city_name",
                              "Standardised Name":"standardised_name",
                              "STATE":"state",
                              "REGION":"region"}, inplace= True)
for object_city_mapping in city_mapping.select_dtypes(include = "object"):
    city_mapping[object_city_mapping] = city_mapping[object_city_mapping].astype("string").str.strip()

city_mapping.drop_duplicates(subset=["original_city_name"], keep= "last", inplace=True)
city_mapping.reset_index(inplace=True)
city_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341 entries, 0 to 340
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               341 non-null    int64
 1   original_city_name  341 non-null    string
 2   standardised_name   341 non-null    string
 3   state               341 non-null    string
 4   region              341 non-null    string
 5   city_id             341 non-null    int64
dtypes: int64(2), string(4)
memory usage: 16.1 KB

## 1. Blinkit

### Prepping the Dump

In [956]:
df_blinkit = pd.read_csv(f"{INPUT_DIR}/blinkit-raw.csv", low_memory=False)

df_blinkit.drop(columns=["Internal SKU"], inplace=True)
df_blinkit = df_blinkit[["item_id", "item_name", "manufacturer_id", "manufacturer_name",
                          "city_id", "city_name", "category", "date", "qty_sold", "mrp"]]

for col in df_blinkit.select_dtypes(include="object"):
    df_blinkit[col] = df_blinkit[col].str.strip().astype("string")

df_blinkit["item_id"]         = pd.to_numeric(df_blinkit["item_id"])
df_blinkit["manufacturer_id"] = pd.to_numeric(df_blinkit["manufacturer_id"])
df_blinkit["city_id"]         = pd.to_numeric(df_blinkit["city_id"])
df_blinkit["qty_sold"]        = pd.to_numeric(df_blinkit["qty_sold"])
df_blinkit["mrp"]             = pd.to_numeric(df_blinkit["mrp"])
df_blinkit["date"]            = pd.to_datetime(df_blinkit["date"], dayfirst=True)

df_blinkit.drop_duplicates(inplace=True)
df_blinkit.sort_values("date", inplace=True)

In [957]:
df_blinkit.rename(columns={"item_id":"blinkit_identifier",
                           "item_name":"blinkit_name",
                           "item_id":"blinkit_identifier",
                           "city_name":"original_city_name"}, inplace=True)

In [958]:
df_blinkit.info()
df_blinkit.head()

<class 'pandas.core.frame.DataFrame'>
Index: 230452 entries, 0 to 230451
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   blinkit_identifier  230452 non-null  int64
 1   blinkit_name        230452 non-null  string
 2   manufacturer_id     230452 non-null  int64
 3   manufacturer_name   230452 non-null  string
 4   city_id             230452 non-null  int64
 5   original_city_name  230452 non-null  string
 6   category            230452 non-null  string
 7   date                230452 non-null  datetime64[ns]
 8   qty_sold            230452 non-null  int64
 9   mrp                 230452 non-null  int64
dtypes: datetime64[ns](1), int64(5), string(4)
memory usage: 19.3 MB

,blinkit_identifier,blinkit_name,manufacturer_id,manufacturer_name,city_id,original_city_name,category,date,qty_sold,mrp
0,14240080,Jaldhara Summer Fiesta Drinks Gift Box (Assort...,1001,Jaldhara Drinks Pvt. Ltd.,2,Mumbai,Cold Drinks & Juices,2023-12-01,3,1647
122,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,125,Panchkula,Sports Drinks,2023-12-01,4,556
123,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,17,Bhopal,Sports Drinks,2023-12-01,1,139
124,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,91,Bahadurgarh,Sports Drinks,2023-12-01,1,139
125,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,178,Karnal,Sports Drinks,2023-12-01,1,139

#### Prepping SKU MAPPING to MERGE with DUMP

In [959]:
sku_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   internal_id           50 non-null     int64
 1   Category              50 non-null     string
 2   internal_name         50 non-null     string
 3   MRP                   50 non-null     int64
 4   blinkit_identifier    22 non-null     float64
 5   blinkit_status        50 non-null     string
 6   instamart_identifier  20 non-null     float64
 7   instamart_status      50 non-null     string
 8   zepto_identifier      37 non-null     string
 9   zepto_status          50 non-null     string
 10  FKM_identifier        10 non-null     string
 11  FKM_status            50 non-null     string
 12  BB_identifier         16 non-null     float64
 13  BB_status             50 non-null     string
dtypes: float64(3), int64(2), string(9)
memory usage: 5.6 KB

In [960]:
sku_mapping_blinkit = sku_mapping[["blinkit_identifier","internal_id","internal_name","Category",'blinkit_status']].copy()
sku_mapping_blinkit.head()

,blinkit_identifier,internal_id,internal_name,Category,blinkit_status
0,16777627.0,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,16274339.0,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,17133772.0,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Live
3,16082268.0,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,18442218.0,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [961]:
blinkit_base = df_blinkit.merge(sku_mapping_blinkit, on="blinkit_identifier", how="left")
blinkit_base.head()

,blinkit_identifier,blinkit_name,manufacturer_id,manufacturer_name,city_id,original_city_name,category,date,qty_sold,mrp,internal_id,internal_name,Category,blinkit_status
0,14240080,Jaldhara Summer Fiesta Drinks Gift Box (Assort...,1001,Jaldhara Drinks Pvt. Ltd.,2,Mumbai,Cold Drinks & Juices,2023-12-01,3,1647,6100,Jaldhara Summer Fiesta Gift Box,Gift Box,Discontinue
1,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,125,Panchkula,Sports Drinks,2023-12-01,4,556,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
2,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,17,Bhopal,Sports Drinks,2023-12-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
3,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,91,Bahadurgarh,Sports Drinks,2023-12-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
4,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,178,Karnal,Sports Drinks,2023-12-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live

#### Merging City Column

In [962]:
blinkit_base = blinkit_base.merge(city_mapping, how = "left", on = "original_city_name")
blinkit_base['platform_id'] = 1
blinkit_base.head()

,blinkit_identifier,blinkit_name,manufacturer_id,manufacturer_name,city_id_x,original_city_name,category,date,qty_sold,mrp,internal_id,internal_name,Category,blinkit_status,index,standardised_name,state,region,city_id_y,platform_id
0,14240080,Jaldhara Summer Fiesta Drinks Gift Box (Assort...,1001,Jaldhara Drinks Pvt. Ltd.,2,Mumbai,Cold Drinks & Juices,2023-12-01,3,1647,6100,Jaldhara Summer Fiesta Gift Box,Gift Box,Discontinue,161.0,Mumbai,Maharashtra,West,405011.0,1
1,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,125,Panchkula,Sports Drinks,2023-12-01,4,556,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,183.0,Panchkula,Haryana,North,202014.0,1
2,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,17,Bhopal,Sports Drinks,2023-12-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,40.0,Bhopal,Madhya Pradesh,West,404001.0,1
3,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,91,Bahadurgarh,Sports Drinks,2023-12-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,19.0,Bahadurgarh,Haryana,North,202002.0,1
4,16777627,Jaldhara Nimbu Shikanji Instant Drink Mix(Pouch),1001,Jaldhara Drinks Pvt. Ltd.,178,Karnal,Sports Drinks,2023-12-01,1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,125.0,Karnal,Haryana,North,202011.0,1

### Final Blinkit DF

In [963]:
blinkit_base = blinkit_base[['platform_id','blinkit_identifier','city_id_y','standardised_name','state','region','date','internal_id','blinkit_status','Category','internal_name','qty_sold','mrp']].copy()
blinkit_base.rename(columns={
                            'blinkit_identifier' : 'platform_sku_id',
                            'date'               : 'sale_date',
                            'city_id_y'          : 'city_id',
                            "internal_id"        : 'internal_sku_id',
                            'standardised_name':'city_name',
                            'Category':'category',
                            "blinkit_status": "status"}, inplace=True)
blinkit_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,1,14240080,405011.0,Mumbai,Maharashtra,West,2023-12-01,6100,Discontinue,Gift Box,Jaldhara Summer Fiesta Gift Box,3,1647
1,1,16777627,202014.0,Panchkula,Haryana,North,2023-12-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,4,556
2,1,16777627,404001.0,Bhopal,Madhya Pradesh,West,2023-12-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139
3,1,16777627,202002.0,Bahadurgarh,Haryana,North,2023-12-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139
4,1,16777627,202011.0,Karnal,Haryana,North,2023-12-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139

## 2. Zepto

In [964]:
df_zepto = pd.read_csv(f"{INPUT_DIR}/zepto-raw.csv", low_memory=False)
df_zepto.head()

,Date,SKU Name,SKU ID,City,Brand Name,Manufacturer ID,Manufacturer Name,SKU Category,Quantity,GMV
0,01/10/2024,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Chennai,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",3,627
1,01/10/2024,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Bengaluru,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",3,627
2,01/10/2024,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Hyderabad,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,209
3,01/10/2024,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Noida,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,209
4,01/10/2024,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Delhi,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,209

In [965]:
df_zepto.rename(columns={
    "Date"           : "date",
    "SKU Name"         : "zepto_name",
    "SKU ID"           : "zepto_identifier",
    "City"           : "original_city_name",
    "Brand Name"       : "brand_name",
    "Manufacturer ID"  : "manufacture_id",
    "Manufacturer Name": "manufacture_name",
    "SKU Category"     : "sku_category",
    "Quantity"         : "quantity",
    "GMV"            : "gmv",
}, inplace=True)

df_zepto["date"] = pd.to_datetime(df_zepto["date"].str.replace("-", "/"), dayfirst=True)

for col in df_zepto.select_dtypes(include="object"):
    df_zepto[col] = df_zepto[col].str.strip().astype("string")

df_zepto.dropna(subset=["quantity"], inplace=True)
df_zepto.sort_values("date", inplace=True)

In [966]:
df_zepto.info()
df_zepto.head()

<class 'pandas.core.frame.DataFrame'>
Index: 34691 entries, 0 to 34690
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                34691 non-null  datetime64[ns]
 1   zepto_name          34691 non-null  string
 2   zepto_identifier    34691 non-null  string
 3   original_city_name  34691 non-null  string
 4   brand_name          34691 non-null  string
 5   manufacture_id      34691 non-null  string
 6   manufacture_name    34691 non-null  string
 7   sku_category        34691 non-null  string
 8   quantity            34691 non-null  int64
 9   gmv                 34691 non-null  int64
dtypes: datetime64[ns](1), int64(2), string(7)
memory usage: 2.9 MB

,date,zepto_name,zepto_identifier,original_city_name,brand_name,manufacture_id,manufacture_name,sku_category,quantity,gmv
0,2024-10-01,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Chennai,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",3,627
104,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",5,695
105,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Puducherry,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139
106,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Vijayawada,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139
107,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Faridabad,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139

#### Prepping SKU MAPPING to MERGE with DUMP

In [967]:
sku_mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   internal_id           50 non-null     int64
 1   Category              50 non-null     string
 2   internal_name         50 non-null     string
 3   MRP                   50 non-null     int64
 4   blinkit_identifier    22 non-null     float64
 5   blinkit_status        50 non-null     string
 6   instamart_identifier  20 non-null     float64
 7   instamart_status      50 non-null     string
 8   zepto_identifier      37 non-null     string
 9   zepto_status          50 non-null     string
 10  FKM_identifier        10 non-null     string
 11  FKM_status            50 non-null     string
 12  BB_identifier         16 non-null     float64
 13  BB_status             50 non-null     string
dtypes: float64(3), int64(2), string(9)
memory usage: 5.6 KB

In [968]:
sku_mapping_zepto = sku_mapping[["zepto_identifier","internal_id","internal_name","Category","zepto_status"]].copy()
sku_mapping_zepto.head()

,zepto_identifier,internal_id,internal_name,Category,zepto_status
0,e60c96b4-afc6-47cd-a732-3317572ba370,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,73316a9f-0bfe-41ae-8a77-1c4b6647ffa1,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,b5e8fcfb-d267-4df8-b54c-1154b6a01027,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Live
3,02f8acdf-bc5e-4970-912e-feadc184c785,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,8497232c-cb60-4d49-9a8c-fc388c0a7b2d,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [969]:
zepto_base = df_zepto.merge(sku_mapping_zepto, on = "zepto_identifier", how = "left")
zepto_base.head()

,date,zepto_name,zepto_identifier,original_city_name,brand_name,manufacture_id,manufacture_name,sku_category,quantity,gmv,internal_id,internal_name,Category,zepto_status
0,2024-10-01,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Chennai,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",3,627,5630,Jaldhara Lemon Electrolyte Pack of 20,Energy Mix,Live
1,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",5,695,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
2,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Puducherry,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
3,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Vijayawada,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
4,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Faridabad,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live

#### Merging Cities

In [970]:
zepto_base = zepto_base.merge(city_mapping, how = "left", on = "original_city_name")
zepto_base['platform_id'] = 2
zepto_base.head()

,date,zepto_name,zepto_identifier,original_city_name,brand_name,manufacture_id,manufacture_name,sku_category,quantity,gmv,internal_id,internal_name,Category,zepto_status,index,standardised_name,state,region,city_id,platform_id
0,2024-10-01,Jaldhara Lemon Electrolyte Instant Drink Mix 2...,1c201250-7a13-4028-9127-732e71dc69cc,Chennai,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",3,627,5630,Jaldhara Lemon Electrolyte Pack of 20,Energy Mix,Live,55.0,Chennai,Tamil Nadu,South,305001.0,2
1,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Kolkata,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",5,695,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,134.0,Kolkata,West Bengal,East,507008.0,2
2,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Puducherry,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,192.0,Pondicherry,Puducherry,South,304001.0,2
3,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Vijayawada,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,261.0,Vijayawada,Andhra Pradesh,South,301012.0,2
4,2024-10-01,Jaldhara Nimbu Shikanji Instant Drink Mix 90.0...,e60c96b4-afc6-47cd-a732-3317572ba370,Faridabad,Jaldhara,ecw23t6e5a-52d2asdf38817-d9fe-4edf-234c,Jaldhara,"Drinks, Beverages",1,139,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,74.0,Faridabad,Haryana,Delhi NCR,102001.0,2

### Final Zepto Dataframe

In [971]:
zepto_base = zepto_base[['platform_id','zepto_identifier','city_id','standardised_name','state','region','date','internal_id',"zepto_status",'Category','internal_name','quantity','gmv']].copy()
zepto_base.rename(columns={
                            'zepto_identifier' : 'platform_sku_id',
                            'date'               : 'sale_date',
                            "internal_id"        : 'internal_sku_id',
                            'standardised_name':'city_name',
                            "Category":'category',
                            'quantity' : 'qty_sold',
                            'gmv' : 'mrp',
                            "zepto_status":"status"}, inplace=True)
zepto_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,2,1c201250-7a13-4028-9127-732e71dc69cc,305001.0,Chennai,Tamil Nadu,South,2024-10-01,5630,Live,Energy Mix,Jaldhara Lemon Electrolyte Pack of 20,3,627
1,2,e60c96b4-afc6-47cd-a732-3317572ba370,507008.0,Kolkata,West Bengal,East,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,5,695
2,2,e60c96b4-afc6-47cd-a732-3317572ba370,304001.0,Pondicherry,Puducherry,South,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139
3,2,e60c96b4-afc6-47cd-a732-3317572ba370,301012.0,Vijayawada,Andhra Pradesh,South,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139
4,2,e60c96b4-afc6-47cd-a732-3317572ba370,102001.0,Faridabad,Haryana,Delhi NCR,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139

## 3. Instamart

In [972]:
df_instamart = pd.read_csv(f"{INPUT_DIR}/instamart-raw.csv", low_memory=False)


for col in df_instamart.select_dtypes(include="object"):
    df_instamart[col] = df_instamart[col].str.strip().astype("string")

df_instamart.rename(columns={"GMV.1": "GMV",
                             "PRODUCT_NAME": "instamart_name",
                             "ITEM_CODE":"instamart_identifier",
                             "CITY":"original_city_name"}, inplace=True)
df_instamart["ORDERED_DATE"] = pd.to_datetime(df_instamart["ORDERED_DATE"], dayfirst=True, format="mixed")
df_instamart.sort_values("ORDERED_DATE", inplace=True)

In [973]:
df_instamart.info()
df_instamart.head()

<class 'pandas.core.frame.DataFrame'>
Index: 82534 entries, 0 to 82533
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DATE                  82534 non-null  string
 1   ORDERED_DATE          82534 non-null  datetime64[ns]
 2   original_city_name    82534 non-null  string
 3   AREA_NAME             82534 non-null  string
 4   STORE_ID              82534 non-null  int64
 5   L1_CATEGORY           82534 non-null  string
 6   L2_CATEGORY           82534 non-null  string
 7   L3_CATEGORY           82534 non-null  string
 8   instamart_name        82534 non-null  string
 9   VARIANT               82534 non-null  string
 10  instamart_identifier  82534 non-null  int64
 11  COMBO                 82534 non-null  string
 12  COMBO_ITEM_CODE       4899 non-null   float64
 13  COMBO_UNITS_SOLD      4899 non-null   float64
 14  BASE_MRP              82534 non-null  int64
 15  UNITS_SOLD            82534 non-null  int64
 16  GMV                   82534 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(5), string(9)
memory usage: 11.3 MB

,DATE,ORDERED_DATE,original_city_name,AREA_NAME,STORE_ID,L1_CATEGORY,L2_CATEGORY,L3_CATEGORY,instamart_name,VARIANT,instamart_identifier,COMBO,COMBO_ITEM_CODE,COMBO_UNITS_SOLD,BASE_MRP,UNITS_SOLD,GMV
0,chaayos,2024-10-01,Agra,civil lines,1401076,"tea, coffee and more",tea,tea premix,jaldhara masala lime electrolyte instant drink...,330 g,233463,Yes,12312.0,1.0,168,1,168
360,chaayos,2024-10-01,Delhi,vasant kunj,1386536,"tea, coffee and more",tea,tea premix,jaldhara kala namak lemonade - premium instant...,225 g,792374,No,NaN,NaN,299,2,598
359,chaayos,2024-10-01,Delhi,mayur vihar,1404576,"tea, coffee and more",instant drink mixes,ice tea,jaldhara instant watermelon iced drink premix(...,220 g,282593,No,NaN,NaN,119,2,238
358,chaayos,2024-10-01,Delhi,ashok vihar,816651,"tea, coffee and more",tea,tea premix,jaldhara orange electrolyte instant drink mix ...,330 g,901105,No,NaN,NaN,189,3,567
357,chaayos,2024-10-01,Bhopal,mp nagar,1399345,"tea, coffee and more",tea,tea premix,jaldhara orange electrolyte instant drink mix ...,330 g,901105,No,NaN,NaN,189,2,378

#### Prepping SKU MAPPING to MERGE with DUMP

In [974]:
sku_mapping_instamart = sku_mapping[["instamart_identifier","internal_id","internal_name","Category","instamart_status"]].copy()
sku_mapping_instamart.head()

,instamart_identifier,internal_id,internal_name,Category,instamart_status
0,NaN,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Not - Live
1,962270.0,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,313662.0,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Live
3,NaN,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Not - Live
4,792374.0,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [975]:
instamart_base = df_instamart.merge(sku_mapping_instamart, on = "instamart_identifier", how = "left")
instamart_base.head()

,DATE,ORDERED_DATE,original_city_name,AREA_NAME,STORE_ID,L1_CATEGORY,L2_CATEGORY,L3_CATEGORY,instamart_name,VARIANT,...,COMBO,COMBO_ITEM_CODE,COMBO_UNITS_SOLD,BASE_MRP,UNITS_SOLD,GMV,internal_id,internal_name,Category,instamart_status
0,chaayos,2024-10-01,Agra,civil lines,1401076,"tea, coffee and more",tea,tea premix,jaldhara masala lime electrolyte instant drink...,330 g,...,Yes,12312.0,1.0,168,1,168,4858.0,Jaldhara Masala Lime Electrolyte Pack of 20,Energy Mix,Live
1,chaayos,2024-10-01,Delhi,vasant kunj,1386536,"tea, coffee and more",tea,tea premix,jaldhara kala namak lemonade - premium instant...,225 g,...,No,NaN,NaN,299,2,598,3812.0,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live
2,chaayos,2024-10-01,Delhi,mayur vihar,1404576,"tea, coffee and more",instant drink mixes,ice tea,jaldhara instant watermelon iced drink premix(...,220 g,...,No,NaN,NaN,119,2,238,5019.0,Jaldhara Watermelon Iced Drink Mix,Iced Mix,Live
3,chaayos,2024-10-01,Delhi,ashok vihar,816651,"tea, coffee and more",tea,tea premix,jaldhara orange electrolyte instant drink mix ...,330 g,...,No,NaN,NaN,189,3,567,4860.0,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live
4,chaayos,2024-10-01,Bhopal,mp nagar,1399345,"tea, coffee and more",tea,tea premix,jaldhara orange electrolyte instant drink mix ...,330 g,...,No,NaN,NaN,189,2,378,4860.0,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live

#### Merging Cities

In [976]:
instamart_base =instamart_base.merge(city_mapping, how = "left", on = "original_city_name")
instamart_base['platform_id'] = 3
instamart_base.head()

,DATE,ORDERED_DATE,original_city_name,AREA_NAME,STORE_ID,L1_CATEGORY,L2_CATEGORY,L3_CATEGORY,instamart_name,VARIANT,...,internal_id,internal_name,Category,instamart_status,index,standardised_name,state,region,city_id,platform_id
0,chaayos,2024-10-01,Agra,civil lines,1401076,"tea, coffee and more",tea,tea premix,jaldhara masala lime electrolyte instant drink...,330 g,...,4858.0,Jaldhara Masala Lime Electrolyte Pack of 20,Energy Mix,Live,0,Agra,Uttar Pradesh,North,207001,3
1,chaayos,2024-10-01,Delhi,vasant kunj,1386536,"tea, coffee and more",tea,tea premix,jaldhara kala namak lemonade - premium instant...,225 g,...,3812.0,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live,61,Delhi,Delhi,Delhi NCR,101001,3
2,chaayos,2024-10-01,Delhi,mayur vihar,1404576,"tea, coffee and more",instant drink mixes,ice tea,jaldhara instant watermelon iced drink premix(...,220 g,...,5019.0,Jaldhara Watermelon Iced Drink Mix,Iced Mix,Live,61,Delhi,Delhi,Delhi NCR,101001,3
3,chaayos,2024-10-01,Delhi,ashok vihar,816651,"tea, coffee and more",tea,tea premix,jaldhara orange electrolyte instant drink mix ...,330 g,...,4860.0,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live,61,Delhi,Delhi,Delhi NCR,101001,3
4,chaayos,2024-10-01,Bhopal,mp nagar,1399345,"tea, coffee and more",tea,tea premix,jaldhara orange electrolyte instant drink mix ...,330 g,...,4860.0,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live,40,Bhopal,Madhya Pradesh,West,404001,3

### Final Instamart Dataframe

In [977]:
instamart_base = instamart_base[['platform_id','instamart_identifier','city_id','standardised_name','state','region','ORDERED_DATE','internal_id','instamart_status','Category','internal_name','UNITS_SOLD','GMV']].copy()
instamart_base.rename(columns={
                            'instamart_identifier' : 'platform_sku_id',
                            'ORDERED_DATE'               : 'sale_date',
                            "internal_id"        : 'internal_sku_id',
                            'standardised_name':'city_name',
                            'Category':'category',
                            'UNITS_SOLD':"qty_sold",
                            "GMV":'mrp',
                            'instamart_status':"status"}, inplace=True)
instamart_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,3,233463,207001,Agra,Uttar Pradesh,North,2024-10-01,4858.0,Live,Energy Mix,Jaldhara Masala Lime Electrolyte Pack of 20,1,168
1,3,792374,101001,Delhi,Delhi,Delhi NCR,2024-10-01,3812.0,Live,Lemonade,Jaldhara Kala Namak Lemonade Mix 225g,2,598
2,3,282593,101001,Delhi,Delhi,Delhi NCR,2024-10-01,5019.0,Live,Iced Mix,Jaldhara Watermelon Iced Drink Mix,2,238
3,3,901105,101001,Delhi,Delhi,Delhi NCR,2024-10-01,4860.0,Live,Energy Mix,Jaldhara Orange Electrolyte Pack of 20,3,567
4,3,901105,404001,Bhopal,Madhya Pradesh,West,2024-10-01,4860.0,Live,Energy Mix,Jaldhara Orange Electrolyte Pack of 20,2,378

## 4. FK Minutes

In [978]:
df_fkminutes = pd.read_csv(f"{INPUT_DIR}/fkminutes-raw.csv", low_memory=False)


for col in df_fkminutes.select_dtypes(include="object"):
    df_fkminutes[col] = df_fkminutes[col].str.strip().astype("string")

# Normalise date string and truncate to date part only
df_fkminutes["order_date_time"] = (
    df_fkminutes["order_date_time"]
    .str.replace("-", "/")
    .str[:10]
)
df_fkminutes["order_date_time"] = pd.to_datetime(df_fkminutes["order_date_time"], dayfirst=True, format="mixed")
df_fkminutes.sort_values("order_date_time", inplace=True)

In [979]:
df_fkminutes.rename(columns={"product_id":"FKM_identifier",
                             "city":"original_city_name"}, inplace = True)

In [980]:
df_fkminutes.info()
df_fkminutes.head()

<class 'pandas.core.frame.DataFrame'>
Index: 5958 entries, 0 to 5957
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   BrandName_gsheet         5958 non-null   string
 1   order_date_time          5958 non-null   datetime64[ns]
 2   original_city_name       5957 non-null   string
 3   FKM_identifier           5958 non-null   string
 4   analytic_business_unit   5958 non-null   string
 5   analytic_super_category  5958 non-null   string
 6   analytic_vertical        5958 non-null   string
 7   brand_csv                5958 non-null   string
 8   units                    5958 non-null   int64
 9   mrp                      5958 non-null   int64
dtypes: datetime64[ns](1), int64(2), string(7)
memory usage: 512.0 KB

,BrandName_gsheet,order_date_time,original_city_name,FKM_identifier,analytic_business_unit,analytic_super_category,analytic_vertical,brand_csv,units,mrp
0,Jaldhara,2024-10-01,Patna,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139
22,Jaldhara,2024-10-01,Bangalore,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,5,695
21,Jaldhara,2024-10-01,Kolkata,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139
20,Jaldhara,2024-10-01,Delhi,COOLK89IUXAK4R2G,BGM,FoodAndNutrition,Drinks,Jaldhara,4,1396
18,Jaldhara,2024-10-01,Mumbai,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,3,417

### Prepping SKU MAPPING to MERGE with DUMP

In [981]:
sku_mapping_fkminutes = sku_mapping[["FKM_identifier","internal_id","internal_name","Category","FKM_status"]].copy()
sku_mapping_fkminutes.head()

,FKM_identifier,internal_id,internal_name,Category,FKM_status
0,COOLHGI1JNYT7RPW,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,COOLNYFX4M8T1QOJ,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,<NA>,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Not - Live
3,COOL9TQ6V9MH7F2V,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,COOLGDGYP7WFWNEO,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [982]:
fkminutes_base = df_fkminutes.merge(sku_mapping_fkminutes, on = "FKM_identifier", how = "left")
fkminutes_base.head()

,BrandName_gsheet,order_date_time,original_city_name,FKM_identifier,analytic_business_unit,analytic_super_category,analytic_vertical,brand_csv,units,mrp,internal_id,internal_name,Category,FKM_status
0,Jaldhara,2024-10-01,Patna,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
1,Jaldhara,2024-10-01,Bangalore,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,5,695,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
2,Jaldhara,2024-10-01,Kolkata,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
3,Jaldhara,2024-10-01,Delhi,COOLK89IUXAK4R2G,BGM,FoodAndNutrition,Drinks,Jaldhara,4,1396,6106,Jaldhara Premium Kokum Sherbet 450g,Sherbet,Live
4,Jaldhara,2024-10-01,Mumbai,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,3,417,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live

#### Merging Cities

In [983]:
fkminutes_base = fkminutes_base.merge(city_mapping, how = "left", on = "original_city_name")
fkminutes_base['platform_id'] = 4
fkminutes_base.head()

,BrandName_gsheet,order_date_time,original_city_name,FKM_identifier,analytic_business_unit,analytic_super_category,analytic_vertical,brand_csv,units,mrp,internal_id,internal_name,Category,FKM_status,index,standardised_name,state,region,city_id,platform_id
0,Jaldhara,2024-10-01,Patna,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live,187.0,Patna,Bihar,East,502011.0,4
1,Jaldhara,2024-10-01,Bangalore,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,5,695,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,21.0,Bangalore,Karnataka,South,302002.0,4
2,Jaldhara,2024-10-01,Kolkata,COOL9TQ6V9MH7F2V,BGM,FoodAndNutrition,Drinks,Jaldhara,1,139,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live,134.0,Kolkata,West Bengal,East,507008.0,4
3,Jaldhara,2024-10-01,Delhi,COOLK89IUXAK4R2G,BGM,FoodAndNutrition,Drinks,Jaldhara,4,1396,6106,Jaldhara Premium Kokum Sherbet 450g,Sherbet,Live,61.0,Delhi,Delhi,Delhi NCR,101001.0,4
4,Jaldhara,2024-10-01,Mumbai,COOLHGI1JNYT7RPW,BGM,FoodAndNutrition,Drinks,Jaldhara,3,417,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live,161.0,Mumbai,Maharashtra,West,405011.0,4

### Final Flipkart Minutes Dataframe

In [984]:
fkminutes_base = fkminutes_base[['platform_id','FKM_identifier','city_id','standardised_name','state','region','order_date_time','internal_id',"FKM_status",'Category','internal_name','units','mrp']].copy()
fkminutes_base.rename(columns={
                            'FKM_identifier'       : 'platform_sku_id',
                            'order_date_time'      : 'sale_date',
                            "internal_id"          : 'internal_sku_id',
                            'standardised_name'    : 'city_name',
                            'Category'             : 'category',
                            'units'                : "qty_sold",
                            "FKM_status"           :  "status"}, inplace=True)
fkminutes_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp
0,4,COOL9TQ6V9MH7F2V,502011.0,Patna,Bihar,East,2024-10-01,2309,Live,Lemonade,Jaldhara Kala Namak Lemonade Mix 90g,1,139
1,4,COOLHGI1JNYT7RPW,302002.0,Bangalore,Karnataka,South,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,5,695
2,4,COOL9TQ6V9MH7F2V,507008.0,Kolkata,West Bengal,East,2024-10-01,2309,Live,Lemonade,Jaldhara Kala Namak Lemonade Mix 90g,1,139
3,4,COOLK89IUXAK4R2G,101001.0,Delhi,Delhi,Delhi NCR,2024-10-01,6106,Live,Sherbet,Jaldhara Premium Kokum Sherbet 450g,4,1396
4,4,COOLHGI1JNYT7RPW,405011.0,Mumbai,Maharashtra,West,2024-10-01,2310,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,3,417

## 5. Big Basket

In [985]:
df_bigbasket = pd.read_csv(f"{INPUT_DIR}/big-basket-raw.csv", low_memory=False)


for col in df_bigbasket.select_dtypes(include="object"):
    df_bigbasket[col] = df_bigbasket[col].str.strip().astype("string")

# Big Basket provides a date range string (YYYYMMDD) — split into start and end dates
df_bigbasket["start_date"] = pd.to_datetime(df_bigbasket["date_range"].str[:8],  format="%Y%m%d", errors="coerce")
df_bigbasket["end_date"]   = pd.to_datetime(df_bigbasket["date_range"].str[-8:], format="%Y%m%d", errors="coerce")

df_bigbasket = df_bigbasket[["start_date", "end_date", "date_range", "source_city_name", "brand_name",
                              "top_slug", "mid_slug", "leaf_slug", "source_sku_id", "sku_description",
                              "sku_weight", "total_quantity", "total_mrp", "total_sales"]]

In [986]:
df_bigbasket.rename(columns={"source_sku_id":"BB_identifier",
                             "source_city_name":"original_city_name"}, inplace=True)

In [987]:
df_bigbasket.info()
df_bigbasket.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   start_date          415 non-null    datetime64[ns]
 1   end_date            415 non-null    datetime64[ns]
 2   date_range          415 non-null    string
 3   original_city_name  415 non-null    string
 4   brand_name          415 non-null    string
 5   top_slug            415 non-null    string
 6   mid_slug            415 non-null    string
 7   leaf_slug           415 non-null    string
 8   BB_identifier       415 non-null    int64
 9   sku_description     415 non-null    string
 10  sku_weight          415 non-null    string
 11  total_quantity      415 non-null    int64
 12  total_mrp           415 non-null    int64
 13  total_sales         415 non-null    float64
dtypes: datetime64[ns](2), float64(1), int64(3), string(8)
memory usage: 45.5 KB

,start_date,end_date,date_range,original_city_name,brand_name,top_slug,mid_slug,leaf_slug,BB_identifier,sku_description,sku_weight,total_quantity,total_mrp,total_sales
0,2025-10-01,2025-10-31,20251001 - 20251031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,47448644,Jaldhara rose-sharbat-concentrate 150 g,150 g,61,11539,9480.20
1,2025-10-01,2025-10-31,20251001 - 20251031,Gurgaon,Jaldhara,beverages,tea,leaf-dust-tea,40929456,Jaldhara kala-namak-lemonade-instant-drink-mix...,225 g,2,658,558.00
2,2025-10-01,2025-10-31,20251001 - 20251031,Mumbai,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,48004382,Jaldhara instant-orange-electrolyte-drink-mix ...,330 g,8,1512,1329.11
3,2025-10-01,2025-10-31,20251001 - 20251031,Mumbai,Jaldhara,beverages,energy-soft-drinks,icetea-non-aerated-drink,42410255,Jaldhara instant-mango-iced-drink-premix 220 g...,220 g,27,3213,2588.47
4,2025-10-01,2025-10-31,20251001 - 20251031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,43792419,Jaldhara kewra-sharbat-concentrate-herbal-drin...,150 g,23,4807,3922.35

### Prepping SKU MAPPING to MERGE with DUMP

In [988]:
sku_mapping_bigbasket = sku_mapping[["BB_identifier","internal_id","internal_name","Category","BB_status"]].copy()
sku_mapping_bigbasket.head()

,BB_identifier,internal_id,internal_name,Category,BB_status
0,43635493.0,2310,Jaldhara Nimbu Shikanji Mix 90g,Lemonade,Live
1,40127838.0,3814,Jaldhara Nimbu Shikanji Mix 225g,Lemonade,Live
2,NaN,4102,Jaldhara Nimbu Shikanji Mix 450g,Lemonade,Not - Live
3,42980060.0,2309,Jaldhara Kala Namak Lemonade Mix 90g,Lemonade,Live
4,40929456.0,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live

In [989]:
bigbasket_base = df_bigbasket.merge(sku_mapping_bigbasket, on = "BB_identifier", how = "left")
bigbasket_base.head()

,start_date,end_date,date_range,original_city_name,brand_name,top_slug,mid_slug,leaf_slug,BB_identifier,sku_description,sku_weight,total_quantity,total_mrp,total_sales,internal_id,internal_name,Category,BB_status
0,2025-10-01,2025-10-31,20251001 - 20251031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,47448644,Jaldhara rose-sharbat-concentrate 150 g,150 g,61,11539,9480.20,1870,Jaldhara Rose Sherbet Mix,Sherbet,Live
1,2025-10-01,2025-10-31,20251001 - 20251031,Gurgaon,Jaldhara,beverages,tea,leaf-dust-tea,40929456,Jaldhara kala-namak-lemonade-instant-drink-mix...,225 g,2,658,558.00,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live
2,2025-10-01,2025-10-31,20251001 - 20251031,Mumbai,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,48004382,Jaldhara instant-orange-electrolyte-drink-mix ...,330 g,8,1512,1329.11,4860,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live
3,2025-10-01,2025-10-31,20251001 - 20251031,Mumbai,Jaldhara,beverages,energy-soft-drinks,icetea-non-aerated-drink,42410255,Jaldhara instant-mango-iced-drink-premix 220 g...,220 g,27,3213,2588.47,5021,Jaldhara Mango Iced Drink Mix,Iced Mix,Live
4,2025-10-01,2025-10-31,20251001 - 20251031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,43792419,Jaldhara kewra-sharbat-concentrate-herbal-drin...,150 g,23,4807,3922.35,3560,Jaldhara Kewra Sherbet Mix,Sherbet,Live

#### Merging Cities

In [990]:
bigbasket_base = bigbasket_base.merge(city_mapping, how = "left", on = "original_city_name")
bigbasket_base['platform_id'] = 4
bigbasket_base.head()

,start_date,end_date,date_range,original_city_name,brand_name,top_slug,mid_slug,leaf_slug,BB_identifier,sku_description,...,internal_id,internal_name,Category,BB_status,index,standardised_name,state,region,city_id,platform_id
0,2025-10-01,2025-10-31,20251001 - 20251031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,47448644,Jaldhara rose-sharbat-concentrate 150 g,...,1870,Jaldhara Rose Sherbet Mix,Sherbet,Live,21,Bangalore,Karnataka,South,302002,4
1,2025-10-01,2025-10-31,20251001 - 20251031,Gurgaon,Jaldhara,beverages,tea,leaf-dust-tea,40929456,Jaldhara kala-namak-lemonade-instant-drink-mix...,...,3812,Jaldhara Kala Namak Lemonade Mix 225g,Lemonade,Live,282,Gurgaon,Haryana,North,202006,4
2,2025-10-01,2025-10-31,20251001 - 20251031,Mumbai,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,48004382,Jaldhara instant-orange-electrolyte-drink-mix ...,...,4860,Jaldhara Orange Electrolyte Pack of 20,Energy Mix,Live,161,Mumbai,Maharashtra,West,405011,4
3,2025-10-01,2025-10-31,20251001 - 20251031,Mumbai,Jaldhara,beverages,energy-soft-drinks,icetea-non-aerated-drink,42410255,Jaldhara instant-mango-iced-drink-premix 220 g...,...,5021,Jaldhara Mango Iced Drink Mix,Iced Mix,Live,161,Mumbai,Maharashtra,West,405011,4
4,2025-10-01,2025-10-31,20251001 - 20251031,Bangalore,Jaldhara,gourmet-world-food,drinks-beverages,gourmet-tea-tea-Mixs,43792419,Jaldhara kewra-sharbat-concentrate-herbal-drin...,...,3560,Jaldhara Kewra Sherbet Mix,Sherbet,Live,21,Bangalore,Karnataka,South,302002,4

In [991]:
bigbasket_base = bigbasket_base[['platform_id','BB_identifier','city_id','standardised_name','state','region','end_date','internal_id',"BB_status",'Category','internal_name','total_quantity','total_mrp']].copy()
bigbasket_base.rename(columns={
                            'BB_identifier'       : 'platform_sku_id',
                            'end_date'      : 'sale_date',
                            "internal_id"          : 'internal_sku_id',
                            'standardised_name'    : 'city_name',
                            'total_quantity'                : "qty_sold",
                            "internal_name"       :      "internal_sku_name",
                            'Category'      :   'category',
                            "total_mrp"                  : 'mrp',
                            "BB_status" : "sku_status"}, inplace=True)
bigbasket_base.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,sku_status,category,internal_sku_name,qty_sold,mrp
0,4,47448644,302002,Bangalore,Karnataka,South,2025-10-31,1870,Live,Sherbet,Jaldhara Rose Sherbet Mix,61,11539
1,4,40929456,202006,Gurgaon,Haryana,North,2025-10-31,3812,Live,Lemonade,Jaldhara Kala Namak Lemonade Mix 225g,2,658
2,4,48004382,405011,Mumbai,Maharashtra,West,2025-10-31,4860,Live,Energy Mix,Jaldhara Orange Electrolyte Pack of 20,8,1512
3,4,42410255,405011,Mumbai,Maharashtra,West,2025-10-31,5021,Live,Iced Mix,Jaldhara Mango Iced Drink Mix,27,3213
4,4,43792419,302002,Bangalore,Karnataka,South,2025-10-31,3560,Live,Sherbet,Jaldhara Kewra Sherbet Mix,23,4807

In [992]:
fact_sales = pd.concat([blinkit_base, zepto_base, instamart_base, fkminutes_base, bigbasket_base], ignore_index= True)
fact_sales.head()

,platform_id,platform_sku_id,city_id,city_name,state,region,sale_date,internal_sku_id,status,category,internal_name,qty_sold,mrp,sku_status,internal_sku_name
0,1,14240080,405011.0,Mumbai,Maharashtra,West,2023-12-01,6100.0,Discontinue,Gift Box,Jaldhara Summer Fiesta Gift Box,3,1647,<NA>,<NA>
1,1,16777627,202014.0,Panchkula,Haryana,North,2023-12-01,2310.0,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,4,556,<NA>,<NA>
2,1,16777627,404001.0,Bhopal,Madhya Pradesh,West,2023-12-01,2310.0,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139,<NA>,<NA>
3,1,16777627,202002.0,Bahadurgarh,Haryana,North,2023-12-01,2310.0,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139,<NA>,<NA>
4,1,16777627,202011.0,Karnal,Haryana,North,2023-12-01,2310.0,Live,Lemonade,Jaldhara Nimbu Shikanji Mix 90g,1,139,<NA>,<NA>

In [993]:
fact_sales['city_id']         = fact_sales['city_id'].astype('Int64')
fact_sales['internal_sku_id'] = fact_sales['internal_sku_id'].astype('Int64')
fact_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354050 entries, 0 to 354049
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   platform_id        354050 non-null  int64
 1   platform_sku_id    354050 non-null  object
 2   city_id            352772 non-null  Int64
 3   city_name          352772 non-null  string
 4   state              352772 non-null  string
 5   region             352772 non-null  string
 6   sale_date          354050 non-null  datetime64[ns]
 7   internal_sku_id    354023 non-null  Int64
 8   status             353608 non-null  string
 9   category           354023 non-null  string
 10  internal_name      353608 non-null  string
 11  qty_sold           354050 non-null  int64
 12  mrp                354050 non-null  int64
 13  sku_status         415 non-null     string
 14  internal_sku_name  415 non-null     string
dtypes: Int64(2), datetime64[ns](1), int64(3), object(1), string(8)
memory usage: 41.2+ MB

In [994]:
fact_sales[fact_sales["sku_status"]=="Not - Live"]

Empty DataFrame
Columns: [platform_id, platform_sku_id, city_id, city_name, state, region, sale_date, internal_sku_id, status, category, internal_name, qty_sold, mrp, sku_status, internal_sku_name]
Index: []

## SQL DATABASE CREATION

In [995]:
# Connecting with the server
password = quote_plus("#Arti14@")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/jaldhara_db")

In [996]:
fact_sales.to_sql(
    name      = "fact_sales",
    con       = engine,
    if_exists = "replace",
    index     = False,
    dtype     = {
        "platform_id"       : sqlalchemy.types.SmallInteger(),
        "platform_sku_id"   : sqlalchemy.types.VARCHAR(100),
        "city_id"           : sqlalchemy.types.VARCHAR(20),
        "city_name"         : sqlalchemy.types.VARCHAR(100),
        "state"             : sqlalchemy.types.VARCHAR(100),
        "region"            : sqlalchemy.types.VARCHAR(50),
        "sale_date"         : sqlalchemy.types.Date(),
        "internal_sku_id"   : sqlalchemy.types.Integer(),
        "sku_status"        : sqlalchemy.types.VARCHAR(20),
        "category"          : sqlalchemy.types.VARCHAR(50),
        "internal_sku_name" : sqlalchemy.types.VARCHAR(200),
        "qty_sold"          : sqlalchemy.types.Integer(),
        "mrp"               : sqlalchemy.types.Numeric(10, 2),
    }
)

354050